[package]
name = "my_structures"
version = "0.1.0"
edition = "2021"
authors = ["Victor Fiamoncini <victor.fiamoncini@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "array"
path = "src/array/main.rs"

[dependencies]
